skills:
  stealth:
    name: Stealth
    description: "The ability to move silently and unnoticed, making you a master of covert operations."
    startingLevel: 3
    icon: img/skills/stealth.png
  speed:
    name: Speed
    description: Allows you to move swiftly and efficiently, making you a formidable force in any race or pursuit.
    icon: img/skills/speed.png
    startingLevel: 2
  jovialty:
    name: Jovialty
    description: The art of engaging with people positively and spreading good vibes, creating an atmosphere of joy and positivity wherever you go.
    icon: img/skills/jovialty.png
    startingLevel: 0
skillOptions:
  xpPerLevel: 10
  notifyLevelUp: false
skillChecks:
  rollRange: 100
  skillMultiplier: 10
  failureChance: 1
  difficultyText:
    - - 0
      - Very Easy
    - - 10
      - Easy
    - - 30
      - Medium
    - - 50
      - Hard
    - - 70
      - Very Hard
    - - 80
      - Extremely Hard
    - - 90
      - Near Impossible
